### PR TITLE
[irods/irods#6412] Bump version to 4.3.1 (main)

### PR DESCRIPTION
**Pull request by korydraughn**

### CODE REVIEW

**Review by trel — COMMENTED** [review]
i think this is correct.   the addition of the EXACT is probably right - but i defer.

**Comment by korydraughn** [comment]
I just copied what I saw in some of the other repos.

Can change if necessary.

**Review by alanking — APPROVED** [review]
We haven't specified it everywhere, but it is indeed the case that the plugins (for the most part) require an exact version of the server.

\# it

**Comment by korydraughn** [comment]
#'d

**Pull request merged**
