### PR TITLE
Plugin does not crash agent on unsupported rule text (4-2-stable)

### PR DESCRIPTION
**Pull request by korydraughn**
Cannot provide a test without introducing a dependency on the PREP. Introducing a dependency for running the tests doesn't seem bad, we just need to make the iRODS test hook install it.

Verified at the bench that the issue is resolved with this change.

All tests pass at the bench.

### CODE REVIEW

**Comment by trel** [comment]
this seems pretty straightforward.   clean fix/workaround.

**Review by alanking — COMMENTED** [review]
Seems good to me.

If the REP was *crashing* when a malformed rule is passed to/through it (i.e. no closing curly brace) then can't the test be that an error is returned when a malformed rule is passed in? Don't think we necessarily need PREP/a valid rule to test this. Then again, such a test may not seem worth the time. Up to you

**Comment by korydraughn** [comment]
I was definitely overthinking it. I'll add a test.

**Comment by korydraughn** [comment]
Added test. Will run the test suite soon.

**Comment by korydraughn** [comment]
All tests pass at the bench.

**Review by alanking — APPROVED** [review]
Seems good to me

**Comment by korydraughn** [comment]
Added #'s

**Review by alanking — APPROVED** [review]

**Pull request merged**
