### PR TITLE
[#4] Added stream support (master)

### PR DESCRIPTION
**Pull request by korydraughn**

### CODE REVIEW

**Comment by trel** [comment]
a thought - is there a scenario where using the `_except` peps make sense?  we ever care to catch the case when things fail?   update the right bookkeeping somewhere?

**Comment by korydraughn** [comment]
I'm not sure what the except peps would do. The pre peps are responsible for making sure quotas are enforced. If they are doing their job then the except peps aren't needed in regards to the implementation operating correctly.

**Comment by trel** [comment]
fair enough - is this ready to be merged except for the #?

**Comment by korydraughn** [comment]
Yes

**Pull request merged**
