### PR TITLE
[irods/irods#7281] Fix RPM package dependencies

### PR DESCRIPTION
**Pull request by SwooshyCueb**

### CODE REVIEW

**Comment by korydraughn** [comment]
Do these need to be tested or anything?

This and some of the other PRs look like trivial changes.

**Comment by SwooshyCueb** [comment]
The only ones that need testing are the ones in draft mode. The rest are ready for review.

**Review by alanking — APPROVED** [review]
\# it

**Review by korydraughn — APPROVED** [review]

**Comment by SwooshyCueb** [comment]
\#'d

**Pull request merged**
